default: &default
  DATABASE_URL: <%= ENV["DATABASE_URL"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  username: user
  database: app-dev

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
  username: blog
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
